version: '3'
services:
    jonny_client:
        container_name: jonny_client
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        volumes:
            - .:/usr/src/app
        networks:
            - app-network
networks:
    app-network:
        driver: bridge
