version: '3'
services:
    messenger:
        container_name: jonnymessenger
        build:
            context: ./
            dockerfile: Dockerfile
        ports:
            - '5000:5000'
        volumes:
            - .:/usr/src/app
        networks:
            - app-network
networks:
    app-network:
        driver: bridge

volumes:
    webserver:
