name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  run:
    name: Run
    runs-on: self-hosted
    steps:
      - name: nvm use and npm install
        run: npm install
            

        
      - name: docker build
        run: docker-compose build -f docker-compose.yml
        
      - name: docker up
        run: docker-compose up -d
        id: Build

      - name: Run tests
        run: docker ps

      - name: Deploy
        run: docker ps
        
