name: CI

on:
  push:
    branches: [ master ]
    
jobs:
  run:
    name: Run
    runs-on: self-hosted
    steps:
      - name: nvm use and npm install
        run: npm install
        
      - name: docker up
        run: docker-compose up -f docker-compose.yml -d --build --force-recreate
        id: Build

      - name: Run tests
        run: docker ps

      - name: Deploy
        run: docker ps
        
